pom.xml, src/main/java/de/aservo/atlassian/confapi/exception/NoContentException.java, src/main/java/de/aservo/atlassian/confapi/helper/WebAuthenticationHelper.java, src/main/java/de/aservo/atlassian/confapi/model/ErrorCollection.java, src/main/java/de/aservo/atlassian/confapi/model/PopMailServerBean.java, src/main/java/de/aservo/atlassian/confapi/model/SettingsBean.java, src/main/java/de/aservo/atlassian/confapi/model/SmtpMailServerBean.java, src/main/java/de/aservo/atlassian/confapi/util/MailProtocolUtil.java, src/test/java/atlassian/mail/server/DefaultTestMailServer.java, src/test/java/atlassian/mail/server/DefaultTestPopMailServer.java, src/test/java/atlassian/mail/server/DefaultTestPopMailServerImpl.java, src/test/java/atlassian/mail/server/DefaultTestSmtpMailServer.java, src/test/java/atlassian/mail/server/DefaultTestSmtpMailServerImpl.java, src/test/java/atlassian/mail/server/OtherTestMailServer.java, src/test/java/atlassian/mail/server/OtherTestPopMailServer.java, src/test/java/atlassian/mail/server/OtherTestPopMailServerImpl.java, src/test/java/atlassian/mail/server/OtherTestSmtpMailServer.java, src/test/java/atlassian/mail/server/OtherTestSmtpMailServerImpl.java, src/test/java/de/aservo/atlassian/confapi/exception/NoContentExceptionTest.java, src/test/java/de/aservo/atlassian/confapi/helper/WebAuthenticationHelperTest.java, src/test/java/de/aservo/atlassian/confapi/model/ErrorCollectionTest.java, src/test/java/de/aservo/atlassian/confapi/model/PopMailServerBeanTest.java, src/test/java/de/aservo/atlassian/confapi/model/SettingsBeanTest.java, src/test/java/de/aservo/atlassian/confapi/model/SmtpMailServerBeanTest.java, src/test/java/de/aservo/atlassian/confapi/util/MailProtocolUtilTest.java
With this commit the first base for the ConfAPI library has been implemented.
This library includes some adjusted sources of the confluence-confapi-plugin.
Thinks that have been taken over are:
* exception
* helper
The WebAuthenticationHelper is now implemented as a generic interface
that can easily be reused amongst all the plugin although different
Atlassian interfaces are used.
* model
The from-constructor for the settings bean has been removed as there is no
common Atlassian interface for the settings. The other beans have been taken
over.
* util
=> Add initial common files

pom.xml, src/test/java/com/atlassian/mail/server/DefaultTestMailServer.java, src/test/java/com/atlassian/mail/server/DefaultTestPopMailServer.java, src/test/java/com/atlassian/mail/server/DefaultTestPopMailServerImpl.java, src/test/java/com/atlassian/mail/server/DefaultTestSmtpMailServer.java, src/test/java/com/atlassian/mail/server/DefaultTestSmtpMailServerImpl.java, src/test/java/com/atlassian/mail/server/OtherTestMailServer.java, src/test/java/com/atlassian/mail/server/OtherTestPopMailServer.java, src/test/java/com/atlassian/mail/server/OtherTestPopMailServerImpl.java, src/test/java/com/atlassian/mail/server/OtherTestSmtpMailServer.java, src/test/java/com/atlassian/mail/server/OtherTestSmtpMailServerImpl.java, src/test/java/de/aservo/atlassian/confapi/junit/ResourceAssert.java, src/test/java/de/aservo/atlassian/confapi/model/PopMailServerBeanTest.java, src/test/java/de/aservo/atlassian/confapi/model/SettingsBeanTest.java, src/test/java/de/aservo/atlassian/confapi/model/SmtpMailServerBeanTest.java
The contained test data might be useful to use for other unit and integration
tests in the ConfAPI plugins. For that reason, a test JAR containing tests and
test data is now created and deployed together with the library itself.
Furthermore, the test data package for Atlassian mail tests has been renamed as
it has been missing the com prefix.
=> Build tests JAR, rename test data package

src/main/java/de/aservo/atlassian/confapi/constants/ConfAPI.java, src/main/java/de/aservo/atlassian/confapi/model/PopMailServerBean.java, src/main/java/de/aservo/atlassian/confapi/model/SettingsBean.java, src/main/java/de/aservo/atlassian/confapi/model/SmtpMailServerBean.java, src/main/java/de/aservo/atlassian/confapi/model/UserDirectoryBean.java
In order to make sure that names for REST endpoints and JSON beans are
consistent amongst all ConfAPI plugins, an initial version of a constant class
has been implemented.
Using these constants also simplifies testing, e.g. when building URL's in
integration tests.
=> Add ConfAPI constants class

src/main/java/de/aservo/atlassian/confapi/constants/ConfAPI.java
**NEUESTER STAND, SIEHE --> [HIER](https://github.com/aservo/confapi-commons/pull/9#issuecomment-617702160)**
The export constant has been renamed to 'export-import' as it is more intuitive
if one uses the same endpoint for doing both, the export and the import. Also, a
'queue' constant has been added where long running tasks can be queried by their
task uuid.
Der Endpoint ist für Confluence gedacht, die Konstanten sollten aber auch generisch genug sein für Jira oder Bitbucket.
Folgende Endpoints sollen damit umgesetzt werden:
`GET /export-import`
* `201 (Created)` Synchroner Export, Download URL wird im Location Header zurückgegeben
* `202 (Accepted)` Asynchroner Export, Queue URL wird im Location Header zurückgegeben
* diverse Fehlercodes sonst
`PUT /export-import`
* `201 (Created)` …
=> Rename export constant, add queue, reorder

pom.xml, src/main/java/de/aservo/atlassian/confapi/rest/AbstractDirectoriesResourceImpl.java, src/main/java/de/aservo/atlassian/confapi/rest/AbstractPingResourceImpl.java, src/main/java/de/aservo/atlassian/confapi/rest/api/DirectoriesResource.java, src/main/java/de/aservo/atlassian/confapi/rest/api/PingResource.java, src/test/java/de/aservo/atlassian/confapi/rest/AbstractDirectoriesResourceTest.java, src/test/java/de/aservo/atlassian/confapi/rest/AbstractPingResourceTest.java, src/test/java/de/aservo/atlassian/confapi/rest/TestDirectoriesResourceImpl.java
During the process of standardizing the ConfAPI plugins, more and more of the
REST and the underlying service interfaces have moved to the Commons library.
This lead to the current state that the actual (default) implementation of the
resources also can be moved to the Commons library, while the actual service
implementations should be moved (back) to the actual plugins in order to get rid
of fixed Atlassian dependencies in the Commons library (see #13).
This commit contains two PoC's for REST resources that are now implemented in
the Commons library. First the PingResource that does not contain any services
at all and second the DirectoriesResource that uses a custom service only.
While the DirectoryService interface will stay in the Commons library, the
DirectoryServiceImpl will be …
=> Move resource implementation to ConfAPI Commons

doc/CODE_CONVENTIONS.adoc, pom.xml, src/main/java/de/aservo/atlassian/confapi/model/ApplicationLinkBean.java, src/main/java/de/aservo/atlassian/confapi/model/LicenseBean.java, src/main/java/de/aservo/atlassian/confapi/model/LicensesBean.java, src/main/java/de/aservo/atlassian/confapi/model/MailServerPopBean.java, src/main/java/de/aservo/atlassian/confapi/model/MailServerSmtpBean.java, src/test/java/de/aservo/atlassian/confapi/junit/AbstractBeanTest.java, src/test/java/de/aservo/atlassian/confapi/junit/AbstractTest.java, src/test/java/de/aservo/atlassian/confapi/model/ApplicationLinkBeanTest.java, src/test/java/de/aservo/atlassian/confapi/model/DirectoryBeanTest.java, src/test/java/de/aservo/atlassian/confapi/model/LicenseBeanTest.java, src/test/java/de/aservo/atlassian/confapi/model/LicensesBeanTest.java, src/test/java/de/aservo/atlassian/confapi/model/MailServerPopBeanTest.java, src/test/java/de/aservo/atlassian/confapi/model/MailServerSmtpBeanTest.java, src/test/java/de/aservo/atlassian/confapi/model/SettingsBeanTest.java, src/test/java/de/aservo/atlassian/confapi/model/UserBeanTest.java, src/test/java/de/aservo/atlassian/confapi/util/StringUtil.java
This commit is the first step in defining the naming convention for the ConfAPI
artifacts. It defines how the model beans have to be named and provides
automated tests for checking these naming conventions just by extending from the
AbstractBeanTest class in the bean's test class.
This commit also includes some smaller fixes in comments or regarding
standardization.
=> Define bean naming conventions, add tests, fixes

src/main/java/de/aservo/atlassian/confapi/exception/BadRequestException.java, src/main/java/de/aservo/atlassian/confapi/exception/InternalServerErrorException.java, src/main/java/de/aservo/atlassian/confapi/exception/NoContentException.java, src/main/java/de/aservo/atlassian/confapi/exception/NotFoundException.java, src/main/java/de/aservo/atlassian/confapi/exception/api/AbstractClientErrorWebException.java, src/main/java/de/aservo/atlassian/confapi/exception/api/AbstractServerErrorWebException.java, src/main/java/de/aservo/atlassian/confapi/exception/api/AbstractSuccessWebException.java, src/main/java/de/aservo/atlassian/confapi/exception/api/AbstractWebException.java, src/test/java/de/aservo/atlassian/confapi/exception/BadRequestExceptionTest.java, src/test/java/de/aservo/atlassian/confapi/exception/InternalServerErrorExceptionTest.java, src/test/java/de/aservo/atlassian/confapi/exception/NotFoundExceptionTest.java, src/test/java/de/aservo/atlassian/confapi/junit/AbstractWebExceptionTest.java
These web exceptions will be used to represent different results in the services
classes and replace the currently used Atlassian exceptions.
=> Implement generic web exceptions representing HTTP status codes

src/main/java/de/aservo/atlassian/confapi/model/UserBean.java
Also add another example instance to the model class.
=> Exclude UserBean password from equals and hashcode

src/main/java/de/aservo/atlassian/confapi/rest/AbstractLicensesResourceImpl.java, src/main/java/de/aservo/atlassian/confapi/rest/api/LicensesResource.java, src/main/java/de/aservo/atlassian/confapi/service/api/LicensesService.java, src/test/java/de/aservo/atlassian/confapi/rest/AbstractLicensesResourceTest.java, src/test/java/de/aservo/atlassian/confapi/rest/TestLicensesResourceImpl.java
This commit contains models and interface for building common licence
REST resources across all ConfAPI plugins. It has been adapted to the
latest confapi-commons interface structure. In addition, licenseKey String
body was replaced with `LicenseBean`. An additional resource for setting
multiople licenses `LicensesBean` was also added.
=> license handling classes

src/main/java/de/aservo/atlassian/confapi/rest/AbstractLicensesResourceImpl.java, src/main/java/de/aservo/atlassian/confapi/rest/api/LicensesResource.java, src/main/java/de/aservo/atlassian/confapi/service/api/LicensesService.java, src/test/java/de/aservo/atlassian/confapi/rest/AbstractLicensesResourceTest.java
Due to a resource addressing conflict (path + mediatype) the
license resource was redesigned. Now, there is a dedicated
POST addLicense resource which adds a new license to an already
existing license collection.
The PUT setLicenses resource replaces the existing license
collection.
Because of this redesign the 'clear' flag was removed. Clearing
license details is achieved with the setLicenses method.
=> License resource with addLicense method

pom.xml, src/main/java/de/aservo/atlassian/confapi/model/SettingsBean.java, src/test/java/it/de/aservo/atlassian/confapi/rest/ClientApplication.java, src/test/java/it/de/aservo/atlassian/confapi/rest/PingResourceFuncTest.java, src/test/java/it/de/aservo/atlassian/confapi/rest/ResourceBuilder.java, src/test/java/it/de/aservo/atlassian/confapi/rest/SettingsResourceFuncTest.java
This commit introduces abstract integration testing.
Examples are given for 'ping' and 'settings' resources.
The intention is to define all integration tests in the
commons library and only inherit the 'Abstract*ResourceFuncTest'
classes in the actual confapi plugin.
=> Abstract integration tests implementation

src/main/java/de/aservo/atlassian/confapi/model/LicenseBean.java, src/main/java/de/aservo/atlassian/confapi/model/LicensesBean.java, src/test/java/it/de/aservo/atlassian/confapi/rest/AbstractLicenseResourceFuncTest.java, src/test/java/it/de/aservo/atlassian/confapi/rest/AbstractPingResourceFuncTest.java, src/test/java/it/de/aservo/atlassian/confapi/rest/AbstractSettingsResourceFuncTest.java
This commit introduces abstract integration testing for the licenses
resource. In addition, a sample LicenseBean with a generic 3h developer
license is provided as well. The key might need to be replaced on
a regular basis.
Also, the abstract classes for 'ping' and 'settings' resource integration
tests were renamed. For ping, the mediatype was corrected to text/plain.
=> Abstract licenses resource integration tests implementation

src/main/java/de/aservo/atlassian/confapi/model/MailServerPopBean.java, src/main/java/de/aservo/atlassian/confapi/model/MailServerSmtpBean.java, src/test/java/it/de/aservo/atlassian/confapi/rest/AbstractMailServerPopResourceFuncTest.java, src/test/java/it/de/aservo/atlassian/confapi/rest/AbstractMailServerSmtpResourceFuncTest.java
This commit introduces abstract integration testing for the mail server
resources. Two abstract classes are introduced for both smtp and pop mail
servers. The plugin may instantiate either or both of them depending on its
capabilities.
Additional smtp and pop sample beans are provided covering all required field
for live settings update.
=> Abstract mailserver resource integration tests implementation

pom.xml, src/test/java/it/de/aservo/confapi/commons/rest/AbstractLicenseResourceFuncTest.java, src/test/java/it/de/aservo/confapi/commons/rest/AbstractMailServerPopResourceFuncTest.java, src/test/java/it/de/aservo/confapi/commons/rest/AbstractMailServerSmtpResourceFuncTest.java, src/test/java/it/de/aservo/confapi/commons/rest/AbstractPingResourceFuncTest.java, src/test/java/it/de/aservo/confapi/commons/rest/AbstractSettingsResourceFuncTest.java, src/test/java/it/de/aservo/confapi/commons/rest/AbstractUserResourceFuncTest.java, src/test/java/it/de/aservo/confapi/commons/rest/ClientApplication.java, src/test/java/it/de/aservo/confapi/commons/rest/ResourceBuilder.java
In accordance with the other packages in the commons lib the integration tests
package should also follow the new naming strategy.
=> package renaming W/O atlassian

pom.xml
The dependency management will be used to share the same compile but especially
test dependencies across commons and plugins.
=> Introduce dependency management for non-provided dependencies

src/test/java/it/de/aservo/confapi/commons/rest/AbstractUserResourceFuncTest.java
this commit removes the entity equals check after setting a new password. This is because
the password is excluded from the equals check anyway.
=> improvement of users resource integration test

pom.xml, src/test/java/it/de/aservo/confapi/commons/rest/AbstractLicenseResourceFuncTest.java, src/test/java/it/de/aservo/confapi/commons/rest/AbstractMailServerPopResourceFuncTest.java, src/test/java/it/de/aservo/confapi/commons/rest/AbstractMailServerSmtpResourceFuncTest.java, src/test/java/it/de/aservo/confapi/commons/rest/AbstractSettingsResourceFuncTest.java, src/test/java/it/de/aservo/confapi/commons/rest/AbstractUserResourceFuncTest.java
The missing user 'user' has been prepared using a created home ZIP - also called
generated test resources - in the Confluence plugin.
=> Enable ignored integration tests

pom.xml, src/main/java/de/aservo/confapi/commons/constants/ConfAPI.java, src/main/java/de/aservo/confapi/commons/model/AbstractDirectoryBean.java, src/main/java/de/aservo/confapi/commons/model/DirectoriesBean.java, src/main/java/de/aservo/confapi/commons/model/DirectoryCrowdBean.java, src/main/java/de/aservo/confapi/commons/model/DirectoryGenericBean.java, src/main/java/de/aservo/confapi/commons/model/DirectoryInternalBean.java, src/main/java/de/aservo/confapi/commons/model/DirectoryLdapBean.java
Wie besprochen.
Ich hab auch die Directory Konstanten sortiert und angepasst, was zwar zu diesem weniger schönen Konstrukt führt
```
@XmlRootElement(name = ConfAPI.DIRECTORY + '-' + ConfAPI.DIRECTORY_CROWD)
```
Allerdings haben wir so etwas auch schon bei den Mail Servern und dafür können wir die Konstanten nochmal wiederverwenden, wodurch der Mehrwert steigt:
```
@JsonSubTypes({
@Type(value = DirectoryCrowdBean.class, name = ConfAPI.DIRECTORY_CROWD),
@Type(value = DirectoryGenericBean.class, name = ConfAPI.DIRECTORY_GENERIC),
@Type(value = DirectoryInternalBean.class, name = ConfAPI.DIRECTORY_INTERNAL),
@Type(value = DirectoryLdapBean.class, name = ConfAPI.DIRECTORY_LDAP),
})
```
Das "überflüssige" Komma am Ende ist kleiner syntaktischer Zucker, der dazu führt, dass bei Hinzufügungen …
=> Introduce DirectoryGenericBean for 'unsupported' directory types

pom.xml, src/main/java/de/aservo/confapi/commons/rest/AbstractApplicationLinksResourceImpl.java, src/main/java/de/aservo/confapi/commons/rest/api/ApplicationLinksResource.java, src/main/java/de/aservo/confapi/commons/service/api/ApplicationLinksService.java, src/test/java/de/aservo/confapi/commons/rest/AbstractApplicationLinksResourceTest.java
This commit modifies the application link API in order to allow for ignoring authentication
errors while setting up the link. This usually happens if the application to link to has
not setup the link counterpart yet.
=> ApplicationLinks with ignorable authentication errors

pom.xml, src/main/java/de/aservo/confapi/commons/model/ApplicationLinkBean.java
For GET access of application-link resources it is useful to also retrieve the
status of the link, e.g. in order to determine whether setting up the link
actually worked or not.
=> ApplicationLink Status field

pom.xml, src/main/java/de/aservo/confapi/commons/rest/AbstractDirectoriesResourceImpl.java, src/main/java/de/aservo/confapi/commons/rest/AbstractUsersResourceImpl.java, src/main/java/de/aservo/confapi/commons/service/api/DirectoriesService.java, src/main/java/de/aservo/confapi/commons/service/api/UsersService.java, src/test/java/de/aservo/confapi/commons/rest/AbstractDirectoriesResourceTest.java, src/test/java/de/aservo/confapi/commons/rest/AbstractUsersResourceTest.java, src/test/java/de/aservo/confapi/commons/rest/TestDirectoriesResourceImpl.java, src/test/java/de/aservo/confapi/commons/rest/TestUsersResourceImpl.java
Wir haben in den Services, in denen man mehrere Entitäten verarbeiten kann, bisher immer den Plural verwendet.
Übersehen haben wir das scheinbar beim DirectoryService und beim UserService, die ich hiermit angepasst habe.
=> Parent pom 0.0.11 + rename service classes

src/main/java/de/aservo/confapi/commons/util/BeanValidationUtil.java, src/test/java/de/aservo/confapi/commons/util/BeanValidationUtilTest.java
Upon usage of the method `BeanValidationUtil.validate` in Bitbucket it was recognized that the required
javax.el dependencies cannot be provided as maven dependencies for runtime. However, a bitbucket internal
validator must be injected. This commit extracts the validator validation set processing for other
plugins to use when the default validator of the commons lib cannot be used.
=> Bean Validation Extension

src/main/java/de/aservo/confapi/commons/exception/mapper/WebApplicationExceptionMapper.java, src/test/java/de/aservo/confapi/commons/exception/mapper/WebApplicationExceptionMapperTest.java
As the WebApplicationException needs to be instantiated by a Throwable and there
is no way to instantiate it with a String message only, the call `getMessage()`
always returns the `cause.toString` which always contains the exception class
name as a prefix for the actual message.
With this change, this exception class name is always removed from the exception
message again so that ErrorCollections don't contain any technical details
anymore.
=> Improve WebApplicationException mapping

pom.xml, src/main/java/de/aservo/confapi/commons/model/ApplicationLinkBean.java, src/main/java/de/aservo/confapi/commons/rest/AbstractApplicationLinksResourceImpl.java, src/main/java/de/aservo/confapi/commons/rest/api/ApplicationLinksResource.java, src/main/java/de/aservo/confapi/commons/service/api/ApplicationLinksService.java, src/test/java/de/aservo/confapi/commons/rest/AbstractApplicationLinksResourceTest.java
Switched app link id from type long to UUID in order to match Atlassians type scheme.
=> App link id from type long to UUID

src/main/java/de/aservo/confapi/commons/service/api/LicensesService.java
This commit removes the obsolete delete method of the license service. A few namings
were adjusted as well.
=> License service delete methods removed

pom.xml, src/main/java/de/aservo/confapi/commons/exception/mapper/JsonMappingExceptionMapper.java, src/test/java/de/aservo/confapi/commons/exception/mapper/JsonMappingExceptionMapperTest.java
JsonMappingException gibt's bspw. wenn man einen Wert in einem Enum Attribut setzt, der nicht existiert.
Neues Verhalten:
```
{
"errorMessages": [
"Can not construct instance of de.aservo.confapi.crowd.model.ApplicationBean$ApplicationType from String value 'BLAAA': value not one of declared Enum instance names\n at [Source: org.apache.catalina.connector.CoyoteInputStream@2c5d359a; line: 4, column: 16] (through reference chain: de.aservo.confapi.crowd.model.ApplicationBean[\"type\"])"
]
}
```
=> Map JSON mapping exceptions to bad request

doc/CODE_CONVENTIONS.adoc, pom.xml, src/main/java/de/aservo/confapi/commons/model/AbstractMailServerProtocolBean.java, src/main/java/de/aservo/confapi/commons/model/ApplicationLinkBean.java, src/main/java/de/aservo/confapi/commons/model/DirectoriesBean.java, src/main/java/de/aservo/confapi/commons/model/LicenseBean.java, src/main/java/de/aservo/confapi/commons/model/MailServerSmtpBean.java, src/main/java/de/aservo/confapi/commons/rest/AbstractApplicationLinksResourceImpl.java, src/main/java/de/aservo/confapi/commons/rest/AbstractUsersResourceImpl.java, src/main/java/de/aservo/confapi/commons/rest/api/ApplicationLinksResource.java, src/main/java/de/aservo/confapi/commons/rest/api/DirectoriesResource.java, src/main/java/de/aservo/confapi/commons/rest/api/GadgetsResource.java, src/main/java/de/aservo/confapi/commons/rest/api/LicensesResource.java, src/main/java/de/aservo/confapi/commons/rest/api/MailServerPopResource.java, src/main/java/de/aservo/confapi/commons/rest/api/MailServerSmtpResource.java, src/main/java/de/aservo/confapi/commons/rest/api/PingResource.java, src/main/java/de/aservo/confapi/commons/rest/api/SettingsResource.java, src/main/java/de/aservo/confapi/commons/rest/api/UsersResource.java, src/main/java/de/aservo/confapi/commons/service/api/ApplicationLinksService.java, src/main/java/de/aservo/confapi/commons/service/api/DirectoriesService.java, src/main/java/de/aservo/confapi/commons/service/api/GadgetsService.java, src/main/java/de/aservo/confapi/commons/service/api/LicensesService.java, src/main/java/de/aservo/confapi/commons/service/api/MailServerService.java, src/main/java/de/aservo/confapi/commons/service/api/SettingsService.java, src/main/java/de/aservo/confapi/commons/service/api/UsersService.java, src/test/java/de/aservo/confapi/commons/model/MailServerPopBeanTest.java, src/test/java/de/aservo/confapi/commons/model/MailServerSmtpBeanTest.java
Commit 1:
```
Harmonize remaining model attributes
List of changes:
- Make timeout a `Long` and move default value to getter
- Rename UUID `id` attribute to `uuid`
- Rename `ApplicationLinkTypes` enum to be singular
- Change wrong `oneOf` to `anyOf` schema for directories
- Move licenses `products` attribute up as they also serve as an identifier
```
Commit 2:
```
Update Swagger resource documentation
The wording has been harmonized. The summary always explains the method from a
user's perspective while the response descriptions explains from the endpoints
perspective.
Response descriptions have been moved from the general method description to the
actual response descriptions which allows removing redundances (always naming
the bean class again) and prevents Swagger validation errors. …
```
=> Harmonize beans and interfaces

src/main/java/de/aservo/confapi/commons/model/AbstractDirectoryBean.java
Für "die Apps" vielleicht nicht sooo wichtig (müssen es ja nicht einbauen), aber für Crowd schon
=> Add 'created' and 'updated' dates to directory beans

pom.xml, src/main/java/de/aservo/confapi/commons/model/AbstractDirectoryBean.java
this commit adds com.fasterxml.jackson dependencies in order to allow up-to-date
jackson providers to consume model annotations as well. The deprecated
org.codehaus.jackson must still co-exist in order to allow Atlassian apps to consume
the beans as well (Atlassian still ships with these outdated versions)
=> com.fasterxml.jackson support added

src/main/java/de/aservo/confapi/commons/model/AbstractMailServerProtocolBean.java
fix to prevent the  "Conflicting setter definitions for property \"port\"
error when deserializing with jackson
=> fix to prevent the  "Conflicting setter definitions for property"

pom.xml, src/main/java/de/aservo/confapi/commons/constants/ConfAPI.java, src/main/java/de/aservo/confapi/commons/model/SettingsBrandingColorSchemeBean.java, src/main/java/de/aservo/confapi/commons/rest/AbstractSettingsBrandingResourceImpl.java, src/main/java/de/aservo/confapi/commons/rest/api/SettingsBrandingResource.java, src/main/java/de/aservo/confapi/commons/service/api/SettingsBrandingService.java, src/test/java/de/aservo/confapi/commons/model/SettingsBrandingColorSchemeBeanTest.java, src/test/java/de/aservo/confapi/commons/rest/AbstractSettingsBrandingResourceTest.java, src/test/java/de/aservo/confapi/commons/rest/TestSettingsBrandingResourceImpl.java
this commit fixes class names following the agreed naming convention.
I addition the missing REST pathes were added to SettingsBrandingResource
=> Naming and Path fixes for branding API
