aservo/confapi-commons

- pom.xml
- src/main/java/de/aservo/atlassian/confapi/model/LicenseBean.java
- src/main/java/de/aservo/atlassian/confapi/model/LicensesBean.java
- src/main/java/de/aservo/atlassian/confapi/rest/LicenseResourceInterface.java
- src/test/java/de/aservo/atlassian/confapi/model/LicenseBeanTest.java
- src/test/java/de/aservo/atlassian/confapi/model/LicensesBeanTest.java
This commit contains models and interface for building common licence
REST resources across all ConfAPI plugins.
> license handling classes

- src/main/java/de/aservo/atlassian/confapi/rest/api/DirectoriesResource.java
- src/main/java/de/aservo/atlassian/confapi/rest/api/SettingsResource.java
Selbsterklärend; Namenskonvention + Code Cleanup.
> Fix resource interface naming

- pom.xml
- src/main/java/de/aservo/atlassian/confapi/model/DirectoriesBean.java
- src/main/java/de/aservo/atlassian/confapi/model/GadgetBean.java
- src/main/java/de/aservo/atlassian/confapi/model/GadgetsBean.java
- src/main/java/de/aservo/atlassian/confapi/rest/api/DirectoriesResource.java
- src/test/java/de/aservo/atlassian/confapi/model/DirectoriesBeanTest.java
- src/test/java/de/aservo/atlassian/confapi/model/GadgetBeanTest.java
- src/test/java/de/aservo/atlassian/confapi/model/GadgetsBeanTest.java
Raises snapshot version due to API changes
> Fix the respone scheme for getting directories, introduce gadgets

- src/main/java/de/aservo/atlassian/confapi/rest/AbstractSettingsResourceImpl.java
- src/main/java/de/aservo/atlassian/confapi/service/api/SettingsService.java
- src/test/java/de/aservo/atlassian/confapi/rest/AbstractSettingsResourceTest.java
- src/test/java/de/aservo/atlassian/confapi/rest/TestSettingsResourceImpl.java
this commit adds abstract settings resource and interface classes
for confapi plugins to implement
> abstract settings resource classes

- src/main/java/de/aservo/atlassian/confapi/rest/AbstractMailServerResourceImpl.java
- src/main/java/de/aservo/atlassian/confapi/service/api/MailServerService.java
- src/test/java/de/aservo/atlassian/confapi/rest/AbstractMailServerResourceTest.java
- src/test/java/de/aservo/atlassian/confapi/rest/TestMailServerResourceImpl.java
this commit adds abstract mail server resource and interface classes
for confapi plugins to implement
> abstract mail server resource classes

- src/main/java/de/aservo/atlassian/confapi/exception/BadRequestException.java
- src/main/java/de/aservo/atlassian/confapi/exception/InternalServerErrorException.java
- src/main/java/de/aservo/atlassian/confapi/exception/NotFoundException.java
- src/test/java/de/aservo/atlassian/confapi/junit/AbstractExceptionTest.java
Anmerkung von @brettaufheber , dass wir hier wahrscheinlich eher nicht mit Throwable arbeiten wollen. Habe ich nochmal kurz zu gelesen und gehe ich mit konform.
> Replace throwable by Exception

- src/main/java/de/aservo/atlassian/confapi/rest/AbstractGadgetsResourceImpl.java
- src/main/java/de/aservo/atlassian/confapi/rest/api/GadgetsResource.java
- src/main/java/de/aservo/atlassian/confapi/service/api/GadgetsService.java
- src/test/java/de/aservo/atlassian/confapi/rest/AbstractGadgetsResourceTest.java
- src/test/java/de/aservo/atlassian/confapi/rest/TestGadgetsResourceImpl.java
this commit adds abstract gadgets resource and interface classes
for confapi plugins to implement
> abstract gadgets resource classes

- src/main/java/de/aservo/atlassian/confapi/model/UserBean.java
- src/test/java/it/de/aservo/atlassian/confapi/rest/AbstractUserResourceFuncTest.java
This commit introduces abstract integration testing for the users
resources.
An additional default administrator sample bean was added too.
> Abstract users resource integration tests implementation

- src/main/java/de/aservo/confapi/commons/model/ApplicationLinksBean.java
- src/main/java/de/aservo/confapi/commons/model/DirectoriesBean.java
- src/main/java/de/aservo/confapi/commons/model/GadgetsBean.java
In addition, an incorrect bean name was corrected for ApplicationLinksBean
> added missing no args constructors for jackson deserialization

- pom.xml
- src/main/java/de/aservo/confapi/commons/model/DirectoryBean.java
- src/main/java/de/aservo/confapi/commons/rest/AbstractDirectoriesResourceImpl.java
- src/main/java/de/aservo/confapi/commons/rest/api/DirectoriesResource.java
- src/main/java/de/aservo/confapi/commons/service/api/DirectoryService.java
- src/test/java/de/aservo/confapi/commons/rest/AbstractDirectoriesResourceTest.java
This commit harmonizes the directories endpoint definition by adjusting proper
method names (`setDirectories` instead of `setDirectory`) and by introducing the
new `addDirectory` method for appending a new directory.
> Directories endpoint completion

- src/main/java/de/aservo/confapi/commons/model/DirectoryCrowdBean.java
- src/main/java/de/aservo/confapi/commons/model/DirectoryInternalBean.java
- src/main/java/de/aservo/confapi/commons/model/DirectoryLdapBean.java
Bitte auf die einzelnen Commits schauen...
> Improve directory type beans

- README.md
- pom.xml
Trying to fix the warnings during Maven downloads with that new parent pom
> Use parent pom 0.0.10

- pom.xml
- src/main/java/de/aservo/confapi/commons/model/ApplicationLinkBean.java
- src/main/java/de/aservo/confapi/commons/model/GadgetBean.java
Added entity IDs for missing list components 'gadget' and 'applicationLink'
> Entity IDs

- src/main/java/de/aservo/confapi/commons/rest/AbstractApplicationLinksResourceImpl.java
- src/main/java/de/aservo/confapi/commons/rest/api/ApplicationLinksResource.java
- src/main/java/de/aservo/confapi/commons/service/api/ApplicationLinksService.java
- src/test/java/de/aservo/confapi/commons/rest/AbstractApplicationLinksResourceTest.java
API definition and base impl for single PUT requests in collections (applinks)
> Single PUT requests applinks

- src/main/java/de/aservo/confapi/commons/rest/AbstractDirectoriesResourceImpl.java
- src/main/java/de/aservo/confapi/commons/rest/api/DirectoriesResource.java
- src/main/java/de/aservo/confapi/commons/service/api/DirectoriesService.java
- src/test/java/de/aservo/confapi/commons/rest/AbstractDirectoriesResourceTest.java
API definition and base impl for single PUT requests in collections (user directories)
> Single PUT requests directories

- src/main/java/de/aservo/confapi/commons/rest/AbstractGadgetsResourceImpl.java
- src/main/java/de/aservo/confapi/commons/rest/api/GadgetsResource.java
- src/main/java/de/aservo/confapi/commons/service/api/GadgetsService.java
- src/test/java/de/aservo/confapi/commons/rest/AbstractGadgetsResourceTest.java
API definition and base impl for single PUT requests in collections (gadgets)
> Single PUT requests gadgets

- src/main/java/de/aservo/confapi/commons/rest/AbstractApplicationLinksResourceImpl.java
- src/main/java/de/aservo/confapi/commons/rest/api/ApplicationLinksResource.java
- src/main/java/de/aservo/confapi/commons/service/api/ApplicationLinksService.java
- src/test/java/de/aservo/confapi/commons/rest/AbstractApplicationLinksResourceTest.java
API definition and base impl for DELETE request (applinks)
> DELETE request for applinks

- src/main/java/de/aservo/confapi/commons/rest/AbstractLicensesResourceImpl.java
- src/main/java/de/aservo/confapi/commons/rest/api/LicensesResource.java
- src/main/java/de/aservo/confapi/commons/service/api/LicensesService.java
- src/test/java/de/aservo/confapi/commons/rest/AbstractLicensesResourceTest.java
API definition and base impl for single PUT requests in collections (license)
> Single PUT requests license

- src/main/java/de/aservo/confapi/commons/rest/AbstractGadgetsResourceImpl.java
- src/main/java/de/aservo/confapi/commons/rest/api/GadgetsResource.java
- src/main/java/de/aservo/confapi/commons/service/api/GadgetsService.java
- src/test/java/de/aservo/confapi/commons/rest/AbstractGadgetsResourceTest.java
API definition and base impl for DELETE request (gadgets)
NOTE: a few comment typos where fixed along for the applinks API
> DELETE request for gadgets

- src/main/java/de/aservo/confapi/commons/rest/AbstractDirectoriesResourceImpl.java
- src/main/java/de/aservo/confapi/commons/rest/api/ApplicationLinksResource.java
- src/main/java/de/aservo/confapi/commons/rest/api/DirectoriesResource.java
- src/main/java/de/aservo/confapi/commons/service/api/ApplicationLinksService.java
- src/main/java/de/aservo/confapi/commons/service/api/DirectoriesService.java
- src/test/java/de/aservo/confapi/commons/rest/AbstractDirectoriesResourceTest.java
API definition and base impl for DELETE request (directories)
NOTE: a few comment typos where fixed along for the applinks API
> DELETE request for directories

- pom.xml
- src/main/java/de/aservo/confapi/commons/rest/AbstractApplicationLinksResourceImpl.java
- src/main/java/de/aservo/confapi/commons/rest/AbstractDirectoriesResourceImpl.java
- src/main/java/de/aservo/confapi/commons/rest/AbstractGadgetsResourceImpl.java
- src/main/java/de/aservo/confapi/commons/rest/AbstractLicensesResourceImpl.java
- src/main/java/de/aservo/confapi/commons/rest/api/ApplicationLinksResource.java
- src/main/java/de/aservo/confapi/commons/rest/api/DirectoriesResource.java
- src/main/java/de/aservo/confapi/commons/rest/api/GadgetsResource.java
- src/main/java/de/aservo/confapi/commons/rest/api/LicensesResource.java
- src/main/java/de/aservo/confapi/commons/service/api/ApplicationLinksService.java
- src/main/java/de/aservo/confapi/commons/service/api/DirectoriesService.java
- src/main/java/de/aservo/confapi/commons/service/api/GadgetsService.java
- src/main/java/de/aservo/confapi/commons/service/api/LicensesService.java
- src/test/java/de/aservo/confapi/commons/rest/AbstractApplicationLinksResourceTest.java
- src/test/java/de/aservo/confapi/commons/rest/AbstractDirectoriesResourceTest.java
- src/test/java/de/aservo/confapi/commons/rest/AbstractGadgetsResourceTest.java
- src/test/java/de/aservo/confapi/commons/rest/AbstractLicensesResourceTest.java
API definition and base impl for GET by id request for the following
resources:
- Application Links
- Directories
- Gadgets
- Licenses
> GET by id requests for all collection resources

- pom.xml
- src/main/java/de/aservo/confapi/commons/model/AbstractDirectoryBean.java
> Use 'Boolean' for directory active attributes

- pom.xml
> Bump junit from 4.12 to 4.13.1

- src/main/java/de/aservo/confapi/commons/model/AbstractMailServerProtocolBean.java
- src/test/java/de/aservo/confapi/commons/model/AbstractMailServerProtocolBeanTest.java
- src/test/java/de/aservo/confapi/commons/model/MailServerPopBeanTest.java
- src/test/java/de/aservo/confapi/commons/model/MailServerSmtpBeanTest.java
- Allow setting empty description now
- Allow setting port from int and String
- Provide constant for default timeout
> Improve mail server bean methods

- pom.xml
- src/main/java/de/aservo/confapi/commons/constants/ConfAPI.java
- src/main/java/de/aservo/confapi/commons/model/SettingsBrandingColourSchemeBean.java
- src/main/java/de/aservo/confapi/commons/rest/AbstractSettingsBrandingResourceImpl.java
- src/main/java/de/aservo/confapi/commons/rest/api/SettingsBrandingResource.java
- src/main/java/de/aservo/confapi/commons/service/api/BrandingService.java
- src/test/java/de/aservo/confapi/commons/model/SettingsBrandingColourSchemeBeanTest.java
- src/test/java/de/aservo/confapi/commons/rest/AbstractSettingsBrandingResourceTest.java
- src/test/java/de/aservo/confapi/commons/rest/TestSettingsBrandingResourceImpl.java
this commit adds the API definition and beans for product branding. This
includes colour coding, logo and favicon setup.
> branding API implementation

- src/main/java/de/aservo/confapi/commons/constants/ConfAPI.java
New constants for confluence plugin
> Cache Constants added

- .gitignore
- src/main/java/de/aservo/confapi/commons/model/SettingsBean.java
Add contactMessage parameter to SettingsBean
> Add contact message to settings bean.

- src/main/java/de/aservo/confapi/commons/model/SettingsBean.java
Add external user management field to SettingsBean.
> Add external user management field to general settings.

- .github/workflows/ci.yaml
- pom.xml
Also configure Maven to compile for Java 8 to make plugin working on Atlassian instances running with Java 8.
> Upgrade Ubuntu, Java and GitHub Actions versions

- pom.xml
Fix deployment with Nexus Staging plugin by upgrading version.
> Release 0.1.0

- src/main/java/de/aservo/confapi/commons/model/DirectoryDelegatingBean.java
Also add missing group attributes.
> Extend delegating directory bean by flag to disable user auto-creation
